services:
  csharp-backend:
    build:
      context: ./api/
    container_name: csharp-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - image-storage:/shared/images
  ml:
    build:
      context: ./ml/pretrained_pipeline/  # Specify the path to the custom or pretrained model
    container_name: ml
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - image-storage:/shared/images
  client:
    build:
      context: ./client/
    container_name: fontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - image-storage:/shared/images
      
networks:
  app-network:
    driver: bridge

volumes:
  image-storage: