data_collection:
  dataset: "kmader/skin-cancer-mnist-ham10000"
  download_path: "data/raw"

data_processing:
  path:
    metadata_path: "data/raw/HAM10000_metadata.csv"
    image_path_1: "data/raw/HAM10000_images_part_1"
    image_path_2: "data/raw/ham10000_images_part_2"
    processed_path: "data/processed"
  preprocess_images:
    resize: True
    dimensions: [128, 128]
    normalize: True
  combine_image_df: True
  combing_image_and_metadata: True

model_training:
  model:
    name: "microsoft/resnet-50"
    num_of_classes: 7
    output_path: "model/"
  logs:
    path: "logs"
