data_collection:
  dataset: "kmader/skin-cancer-mnist-ham10000"
  download_path: "data/raw"

data_processing:
  path:
    metadata_path: "data/raw/HAM10000_metadata.csv"
    image_path_1: "data/raw/HAM10000_images_part_1"
    image_path_2: "data/raw/ham10000_images_part_2"
    image_path: "data/processed/images"
    processed_path: "data/processed"
  merge_folder: False
  dataset_size:
    train: 0.80
    validation: 0.125
    test: 0.20
  combine_image_df: False
  combing_image_and_metadata: False

model_training:
  path:
    image_path: "data/processed/images"
    train_data: "data/processed/train.csv"
    val_data: "data/processed/val.csv"
    test_data: "data/processed/test.csv"
  model:
    output_name: "custom_model.pth"
    output_path: "../model/"
  logs:
    path: "logs"

model_validation:
  model:
    path: "model/"
    name: "custom_model.pth"
  test_data:
    path: "data/processed"
  logs:
    metrics: "logs/metrics/"
    roc_curve: "logs/roc_curve/"

server:
  model:
    path: "model"
    custom_model: "custom_model.pth"
